#########################################
# slideshow configuration defaults
#
#   override settings in:
#     ~/slideshow.yml in home folder
#        or
#     ./slideshow.yml in working folder


######################
# lets you define default/fallback headers

headers:
  generator: "<%= Slideshow.generator %>"
  author:  Your Name Here
  email:   Your Email Here
  company: Your Company Here
  title:   Your Title Here
  subtitle: Your Subtitle Here
  footer: Your Footer Here
  subfooter: Your Subfooter Here
  date:  "<%= Date.today %>"

  # todo: use nested config?? eg.
  # gradient:
  #   theme: dark
  #   color1:
  gradient-theme:  diagonal
  gradient-colors:  red orange

  # todo: use nested config??
  #
  # SyntaxHighligher (sh) | ultraviolet (uv) | coderay (cr)
  code-engine:  sh
  # Text Mate Hyperlink for Source?
  code-txmt:  false
  # todo: add code-linenumbers??




# your google analytics code  
analytics:
  google: UA-XXX


########################################################3
### text/markup/markdown processing config

# filters to run before markup processing

##
#  check: use _ or -  (can use both?)
#  document here (if auto-converter)
#  note: ruby names CANNOT use dash (-) e.g. must be converted to underscore (_)

filters:
  - skip-end-directive
  - directives_bang_style_to_percent_style
  - directives_percent_style
  - comments-percent-style 
  - leading-headers
  - erb-django-style
  - erb-rename-helper-hack
  - dump_content_to_file_debug_text_erb
  - erb
  - dump_content_to_file_debug_text


